### ISSUE TITLE
建议,全本地化svg处理

### ISSUE THREAD

**Issue by qq1066536** [iconfont-cli/react-native-iconfont-cli#12]
仅有本地svg需要处理时,也必须加入symbol_url,建议做成可选参数,只有本地svg时,也能直接使用这个插件

**Comment by fwh1990** [comment]
也是不错的想法

**Comment by qq1066536** [comment]
@fwh1990  generateComponent 中判断一下data 是否有svg, createIcon 中判断一下是否有symbol_url 就可以了,

**Comment by qq1066536** [comment]
优化已处理
