### ISSUE TITLE
symbol_url 必须要填吗？我只需要用到本地svg

### ISSUE THREAD

**Issue by toutouli** [iconfont-cli/react-native-iconfont-cli#14]
我删除symbol_url字段和把值设为false都会报错，我觉得symbol_url 值作为必填有点局限，我只需要用到本地Svg

**Comment by fwh1990** [comment]
是的，没有考虑到这一点，明天更新一下去除限制

**Comment by ooooweeee** [comment]
这个问题修改了吗？

**Comment by youngjuning** [comment]
这个问题修改了吗？

**Comment by fwh1990** [comment]
react-native-iconfont-cli@2.2.2

**Comment by fwh1990** [comment]
啰嗦一句，iconfont.cn 已经支持多色字体了

**Comment by youngjuning** [comment]
> react-native-iconfont-cli@2.2.2

这个版本有问题，`node_modules/.bin` 下没有生成 iconfont-init、iconfont-rn 这些命令

**Comment by fwh1990** [comment]
> > react-native-iconfont-cli@2.2.2
> 
> 这个版本有问题，`node_modules/.bin` 下没有生成 iconfont-init、iconfont-rn 这些命令

抱歉，太久没弄搞错了，升级到2.2.3
